services:
  qneyrat.hiboutik.property_info_extractor:
    class: Symfony\Component\PropertyInfo\PropertyInfoExtractor
    arguments:
      - []
      - ["@property_info.php_doc_extractor"]

  qneyrat.hiboutik.property_info_cache_extractor:
    class: Symfony\Component\PropertyInfo\PropertyInfoCacheExtractor
    arguments:
      - "@qneyrat.hiboutik.property_info_extractor"
      - "@cache.app"

  qneyrat.hiboutik.object_normalizer:
    class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer
    arguments:
      - ~
      - "@serializer.name_converter.camel_case_to_snake_case"
      - ~
      - "@qneyrat.hiboutik.property_info_cache_extractor"

  qneyrat.hiboutik.serializer:
    class: Symfony\Component\Serializer\Serializer
    arguments:
      - ["@serializer.normalizer.datetime", "@serializer.denormalizer.array", "@qneyrat.hiboutik.object_normalizer"]
